server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.50.135
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 192.168.50.135 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /review # 虚拟主机
    username: zaizi # 用户名
    password: 123456 # 密码
mybatis-plus:
  type-aliases-package: com.zaizi.entity # 别名扫描包
logging:
  level:
    com.zaizi: debug